### ISSUE TITLE
Are all the methods in your paper "Computer-aided diagnosis from weak supervision: A benchmarking study" included in this code package?

### ISSUE THREAD

**Issue by brisker** [melihkandemir/milbundle#1]
I see that in you leave a message: "first commit. some files need to be maintained."

**Comment by melihkandemir** [comment]
No. I added only my own implementation of GPMIL, mi-SVM, and MI-SVM over here. You can find the rest, such as mi-Graph, from http://lamda.nju.edu.cn/
